<a href="https://colab.research.google.com/github/sandeepkhadk/Data-Piepline/blob/main/ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here is the dataset link  in which this notebook is all about: https://www.kaggle.com/datasets/sriharshaeedala/airline-delay/data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

# **EXTRACTION**

In [ ]:
path='/content/drive/MyDrive/Data_Pipeline/Airline_Delay_Cause.csv'

In [ ]:
df = pd.read_csv(path)

In [ ]:
df = pd.read_csv('pathAirline_Delay_Cause.csv')

In [ ]:
df

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",89.0,13.0,2.25,1.60,...,0.0,5.99,2.0,1.0,1375.0,71.0,761.0,118.0,0.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",62.0,10.0,1.97,0.04,...,0.0,7.42,0.0,1.0,799.0,218.0,1.0,62.0,0.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,10.0,2.73,1.18,...,0.0,4.28,1.0,0.0,766.0,56.0,188.0,78.0,0.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",66.0,12.0,3.69,2.27,...,0.0,1.57,1.0,1.0,1397.0,471.0,320.0,388.0,0.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",92.0,22.0,7.76,0.00,...,0.0,11.28,2.0,0.0,1530.0,628.0,0.0,134.0,0.0,768.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171661,2013,8,YV,Mesa Airlines Inc.,TRI,"Bristol/Johnson City/Kingsport, TN: Tri Cities",7.0,1.0,0.78,0.00,...,0.0,0.00,0.0,0.0,23.0,18.0,0.0,5.0,0.0,0.0
171662,2013,8,YV,Mesa Airlines Inc.,YUM,"Yuma, AZ: Yuma MCAS/Yuma International",2.0,1.0,0.00,0.00,...,0.0,1.00,0.0,0.0,17.0,0.0,0.0,0.0,0.0,17.0
171663,2013,8,YV,Mesa Airlines Inc.,SLC,"Salt Lake City, UT: Salt Lake City International",2.0,0.0,0.00,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
171664,2013,8,DL,Delta Air Lines Inc.,SBN,"South Bend, IN: South Bend International",1.0,1.0,1.00,0.00,...,0.0,0.00,0.0,0.0,18.0,18.0,0.0,0.0,0.0,0.0
171665,2013,8,F9,Frontier Airlines Inc.,MTJ,"Montrose/Delta, CO: Montrose Regional",1.0,0.0,0.00,0.00,...,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
print("Dataset Shape:", df.shape)

Dataset Shape: (171666, 21)

In [ ]:
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2023,8,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",89.0,13.0,2.25,1.60,...,0.0,5.99,2.0,1.0,1375.0,71.0,761.0,118.0,0.0,425.0
1,2023,8,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",62.0,10.0,1.97,0.04,...,0.0,7.42,0.0,1.0,799.0,218.0,1.0,62.0,0.0,518.0
2,2023,8,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,10.0,2.73,1.18,...,0.0,4.28,1.0,0.0,766.0,56.0,188.0,78.0,0.0,444.0
3,2023,8,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",66.0,12.0,3.69,2.27,...,0.0,1.57,1.0,1.0,1397.0,471.0,320.0,388.0,0.0,218.0
4,2023,8,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",92.0,22.0,7.76,0.00,...,0.0,11.28,2.0,0.0,1530.0,628.0,0.0,134.0,0.0,768.0

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 171426 entries, 0 to 171665
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 171426 non-null  int64
 1   month                171426 non-null  int64
 2   carrier              171426 non-null  object
 3   carrier_name         171426 non-null  object
 4   airport              171426 non-null  object
 5   airport_name         171426 non-null  object
 6   arr_flights          171426 non-null  float64
 7   arr_del15            171426 non-null  float64
 8   carrier_ct           171426 non-null  float64
 9   weather_ct           171426 non-null  float64
 10  nas_ct               171426 non-null  float64
 11  security_ct          171426 non-null  float64
 12  late_aircraft_ct     171426 non-null  float64
 13  arr_cancelled        171426 non-null  float64
 14  arr_diverted         171426 non-null  float64
 15  arr_delay            171426 non-null  float64
 16  carrier_delay        171426 non-null  float64
 17  weather_delay        171426 non-null  float64
 18  nas_delay            171426 non-null  float64
 19  security_delay       171426 non-null  float64
 20  late_aircraft_delay  171426 non-null  float64
dtypes: float64(15), int64(2), object(4)
memory usage: 28.8+ MB

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
count,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000,171426.00000,171426.000000,171426.000000,171426.000000,171426.000000,171426.000000
mean,2018.551194,6.492860,362.528467,66.355716,20.796615,2.250347,19.381147,0.157096,23.770554,7.530497,0.863387,4239.48733,1437.185124,222.563497,920.651704,7.382725,1651.700063
std,2.890212,3.440977,992.894662,179.448903,50.315176,7.314252,61.675244,0.717405,72.393477,43.654880,3.772853,12618.56605,4215.677812,821.086511,3423.509335,41.779985,5221.878385
min,2013.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2016.000000,4.000000,50.000000,6.000000,2.160000,0.000000,1.000000,0.000000,1.230000,0.000000,0.000000,335.00000,110.000000,0.000000,34.000000,0.000000,65.000000
50%,2019.000000,7.000000,100.000000,17.000000,6.400000,0.400000,3.910000,0.000000,5.000000,1.000000,0.000000,1018.00000,375.000000,18.000000,146.000000,0.000000,320.000000
75%,2021.000000,9.000000,250.000000,47.000000,17.260000,1.860000,11.710000,0.000000,15.260000,4.000000,1.000000,2884.00000,1109.000000,146.000000,477.000000,0.000000,1070.000000
max,2023.000000,12.000000,21977.000000,4176.000000,1293.910000,266.420000,1884.420000,58.690000,2069.070000,4951.000000,197.000000,438783.00000,196944.000000,31960.000000,112018.000000,3760.000000,227959.000000

In [ ]:
# Check missing values
df.isnull().sum()

year                     0
month                    0
carrier                  0
carrier_name             0
airport                  0
airport_name             0
arr_flights            240
arr_del15              443
carrier_ct             240
weather_ct             240
nas_ct                 240
security_ct            240
late_aircraft_ct       240
arr_cancelled          240
arr_diverted           240
arr_delay              240
carrier_delay          240
weather_delay          240
nas_delay              240
security_delay         240
late_aircraft_delay    240
dtype: int64

# **TRANSFORMATION**

In [ ]:
# Drop rows where arr_flights is missing
df = df.dropna(subset=['arr_flights'])

In [ ]:
df.isnull().sum()

year                     0
month                    0
carrier                  0
carrier_name             0
airport                  0
airport_name             0
arr_flights              0
arr_del15              203
carrier_ct               0
weather_ct               0
nas_ct                   0
security_ct              0
late_aircraft_ct         0
arr_cancelled            0
arr_diverted             0
arr_delay                0
carrier_delay            0
weather_delay            0
nas_delay                0
security_delay           0
late_aircraft_delay      0
dtype: int64

In [ ]:
missing_rows = df[df['arr_del15'].isnull()]
missing_rows

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
16907,2022,10,OO,SkyWest Airlines Inc.,PHL,"Philadelphia, PA: Philadelphia International",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17282,2022,10,YV,Mesa Airlines Inc.,JAN,"Jackson/Vicksburg, MS: Jackson Medgar Wiley Ev...",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27527,2022,4,YV,Mesa Airlines Inc.,MLB,"Melbourne, FL: Melbourne International",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27554,2022,4,YV,Mesa Airlines Inc.,SHV,"Shreveport, LA: Shreveport Regional",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32066,2022,1,OO,SkyWest Airlines Inc.,BOS,"Boston, MA: Logan International",7.0,NaN,0.0,0.0,...,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139150,2015,11,MQ,Envoy Air,BPT,"Beaumont/Port Arthur, TX: Jack Brooks Regional",1.0,NaN,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
148122,2015,3,MQ,Envoy Air,GUC,"Gunnison, CO: Gunnison-Crested Butte Regional",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
150674,2015,1,OO,SkyWest Airlines Inc.,EVV,"Evansville, IN: Evansville Regional",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
162612,2014,3,OO,SkyWest Airlines Inc.,GFK,"Grand Forks, ND: Grand Forks International",1.0,NaN,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
170150,2013,9,EV,ExpressJet Airlines Inc.,TPA,"Tampa, FL: Tampa International",1.0,NaN,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Fill missing arr_del15 with 0 because all other delay depended are 0 in arr_del15 rows i.e. no flight was delayed > 15 min...
df.loc[:, 'arr_del15'] = df['arr_del15'].fillna(0)

In [ ]:
df.isnull().sum()

year                   0
month                  0
carrier                0
carrier_name           0
airport                0
airport_name           0
arr_flights            0
arr_del15              0
carrier_ct             0
weather_ct             0
nas_ct                 0
security_ct            0
late_aircraft_ct       0
arr_cancelled          0
arr_diverted           0
arr_delay              0
carrier_delay          0
weather_delay          0
nas_delay              0
security_delay         0
late_aircraft_delay    0
dtype: int64

In [ ]:
print("Dataset Shape:", df.shape)

Dataset Shape: (171426, 21)

In [ ]:
# Total delay per flight
df.loc[:,'total_delay'] = (
    df['carrier_delay'] +
    df['weather_delay'] +
    df['nas_delay'] +
    df['security_delay'] +
    df['late_aircraft_delay']
)

# Proportion of each delay cause
delay_cols = ['carrier_delay','weather_delay','nas_delay','security_delay','late_aircraft_delay']
for col in delay_cols:
    pct_col = col + '_pct'
    df.loc[:,pct_col] = df[col] / df['total_delay']



# Fill 0 for proportion rows where total_delay = 0
pct_cols = [col + '_pct' for col in delay_cols]
df.loc[:, pct_cols] = df[pct_cols].fillna(0)


# Time features
# Create 'quarter' column based on month (Northen Hemisphere)
# Q1: Jan–Mar → Winter
# Q2: Apr–Jun → Spring
# Q3: Jul–Sep → Summer
# Q4: Oct–Dec → Fall / Autumn

df['month'] = df['month'].astype(int)
df['quarter'] = ((df['month'] - 1) // 3 + 1)

/tmp/ipython-input-520/2362366754.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = df['month'].astype(int)
/tmp/ipython-input-520/2362366754.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['quarter'] = ((df['month'] - 1) // 3 + 1)

In [ ]:
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,nas_delay,security_delay,late_aircraft_delay,total_delay,carrier_delay_pct,weather_delay_pct,nas_delay_pct,security_delay_pct,late_aircraft_delay_pct,quarter
0,2023,8,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",89.0,13.0,2.25,1.60,...,118.0,0.0,425.0,1375.0,0.051636,0.553455,0.085818,0.0,0.309091,3
1,2023,8,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",62.0,10.0,1.97,0.04,...,62.0,0.0,518.0,799.0,0.272841,0.001252,0.077597,0.0,0.648310,3
2,2023,8,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",62.0,10.0,2.73,1.18,...,78.0,0.0,444.0,766.0,0.073107,0.245431,0.101828,0.0,0.579634,3
3,2023,8,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",66.0,12.0,3.69,2.27,...,388.0,0.0,218.0,1397.0,0.337151,0.229062,0.277738,0.0,0.156049,3
4,2023,8,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",92.0,22.0,7.76,0.00,...,134.0,0.0,768.0,1530.0,0.410458,0.000000,0.087582,0.0,0.501961,3

In [ ]:
df[df['total_delay'] == 0].head(10)

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,nas_delay,security_delay,late_aircraft_delay,total_delay,carrier_delay_pct,weather_delay_pct,nas_delay_pct,security_delay_pct,late_aircraft_delay_pct,quarter
25,2023,8,9E,Endeavor Air Inc.,CRW,"Charleston/Dunbar, WV: West Virginia Internati...",5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
40,2023,8,9E,Endeavor Air Inc.,GFK,"Grand Forks, ND: Grand Forks International",1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
56,2023,8,9E,Endeavor Air Inc.,MBS,"Saginaw/Bay City/Midland, MI: MBS International",4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
68,2023,8,9E,Endeavor Air Inc.,OAJ,"Jacksonville/Camp Lejeune, NC: Albert J Ellis",4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
75,2023,8,9E,Endeavor Air Inc.,RAP,"Rapid City, SD: Rapid City Regional",3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
82,2023,8,9E,Endeavor Air Inc.,SDF,"Louisville, KY: Louisville Muhammad Ali Intern...",15.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
86,2023,8,9E,Endeavor Air Inc.,TLH,"Tallahassee, FL: Tallahassee International",2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
258,2023,8,AS,Alaska Airlines Inc.,JAC,"Jackson, WY: Jackson Hole",21.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
505,2023,8,DL,Delta Air Lines Inc.,STX,"Christiansted, VI: Henry E. Rohlsen",4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3
632,2023,8,G4,Allegiant Air,GFK,"Grand Forks, ND: Grand Forks International",9.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3

In [ ]:
df['quarter'].unique()

array([3, 2, 1, 4])

In [ ]:
df['carrier'].unique()

array(['9E', 'AA', 'AS', 'B6', 'DL', 'F9', 'G4', 'HA', 'MQ', 'NK', 'OH',
       'OO', 'UA', 'WN', 'YX', 'QX', 'YV', 'EV', 'VX', 'US', 'FL'],
      dtype=object)

In [ ]:
df['airport'].unique()

array(['ABE', 'ABY', 'AEX', 'AGS', 'ALB', 'ATL', 'AUS', 'AVL', 'AZO',
       'BDL', 'BGM', 'BGR', 'BHM', 'BNA', 'BQK', 'BTV', 'BUF', 'BWI',
       'CAE', 'CHA', 'CHO', 'CHS', 'CLE', 'CLT', 'CMH', 'CRW', 'CSG',
       'CVG', 'CWA', 'DAY', 'DCA', 'DHN', 'DLH', 'DSM', 'DTW', 'EVV',
       'EWR', 'FAR', 'FAY', 'FSD', 'GFK', 'GRR', 'GSO', 'GSP', 'GTR',
       'IAD', 'ILM', 'IND', 'ITH', 'JAX', 'JFK', 'LAN', 'LEX', 'LFT',
       'LGA', 'LIT', 'MBS', 'MCI', 'MEM', 'MGM', 'MKE', 'MLI', 'MLU',
       'MOB', 'MQT', 'MSN', 'MSP', 'MYR', 'OAJ', 'OMA', 'ORF', 'ORH',
       'PIT', 'PVD', 'PWM', 'RAP', 'RDU', 'RIC', 'ROA', 'ROC', 'RST',
       'SAV', 'SDF', 'SHV', 'STL', 'SYR', 'TLH', 'TRI', 'TVC', 'TYS',
       'VLD', 'XNA', 'ABQ', 'AMA', 'ANC', 'AVP', 'BFL', 'BOI', 'BOS',
       'BUR', 'BZN', 'CID', 'COS', 'DAB', 'DEN', 'DFW', 'DRO', 'ECP',
       'EGE', 'ELP', 'EUG', 'EYW', 'FAT', 'FCA', 'FLL', 'GEG', 'HNL',
       'HSV', 'IAH', 'ICT', 'JAC', 'KOA', 'LAS', 'LAX', 'LBB', 'LIH',
       'MCO', 'MDT', 'MFE', 'MHT', 'MIA', 'MRY', 'MSO', 'MSY', 'MTJ',
       'OGG', 'OKC', 'ONT', 'ORD', 'PBI', 'PDX', 'PHL', 'PHX', 'PNS',
       'PSP', 'RNO', 'RSW', 'SAN', 'SAT', 'SBA', 'SBP', 'SEA', 'SFO',
       'SJC', 'SJU', 'SLC', 'SMF', 'SNA', 'SRQ', 'STT', 'STX', 'TPA',
       'TUL', 'TUS', 'VPS', 'ADK', 'ADQ', 'AKN', 'BET', 'BRW', 'CDV',
       'DAL', 'DLG', 'FAI', 'GST', 'JNU', 'KTN', 'OAK', 'OME', 'OTZ',
       'PSC', 'PSG', 'RDM', 'SCC', 'SIT', 'STS', 'WRG', 'YAK', 'ACK',
       'BQN', 'HPN', 'HYA', 'MVY', 'PSE', 'ATW', 'BIL', 'BIS', 'BTR',
       'GNV', 'GPT', 'GRB', 'HOU', 'JAN', 'MDW', 'MLB', 'SGF', 'BMI',
       'ISP', 'TTN', 'AZA', 'BLI', 'BLV', 'CAK', 'CKB', 'ELM', 'FNT',
       'FWA', 'GJT', 'GRI', 'GTF', 'HGR', 'HTS', 'IAG', 'IDA', 'LCK',
       'LRD', 'MFR', 'MOT', 'PBG', 'PGD', 'PIA', 'PIE', 'PSM', 'PVU',
       'RFD', 'SBN', 'SCK', 'SFB', 'SMX', 'SPI', 'SWF', 'TOL', 'USA',
       'ITO', 'LGB', 'PPG', 'ABI', 'BRO', 'CLL', 'CMI', 'COU', 'CRP',
       'FSM', 'GRK', 'HHH', 'HRL', 'MAF', 'SJT', 'YUM', 'ACY', 'LBE',
       'EWN', 'ABR', 'ACT', 'ACV', 'ALW', 'APN', 'ASE', 'BFF', 'BIH',
       'BJI', 'BPT', 'BRD', 'BTM', 'CDC', 'CIU', 'CMX', 'CNY', 'CPR',
       'DDC', 'DEC', 'DIK', 'DVL', 'EKO', 'ESC', 'FLG', 'FOD', 'GCC',
       'GCK', 'GGG', 'GUC', 'HDN', 'HIB', 'HLN', 'HYS', 'IMT', 'INL',
       'JLN', 'JMS', 'JST', 'LAR', 'LAW', 'LBF', 'LBL', 'LCH', 'LNK',
       'LWS', 'MCW', 'MEI', 'OTH', 'PIB', 'PIH', 'PLN', 'PRC', 'RDD',
       'RHI', 'RIW', 'RKS', 'ROW', 'SAF', 'SCE', 'SGU', 'SHR', 'SLN',
       'SPS', 'SUN', 'SUX', 'SWO', 'TWF', 'TXK', 'TYR', 'VCT', 'VEL',
       'WYS', 'XWA', 'GUM', 'SPN', 'LSE', 'PAE', 'ERI', 'OWB', 'STC',
       'MHK', 'PGV', 'COD', 'CYS', 'DRT', 'ALO', 'PUB', 'PHF', 'PAH',
       'EAT', 'PUW', 'YKM', 'FLO', 'EAU', 'LYH', 'CGI', 'EAR', 'LWB',
       'SHD', 'TBN', 'IFP', 'DBQ', 'MKG', 'BKG', 'ILG', 'ALS', 'HOB',
       'OGS', 'OGD', 'ATY', 'PIR', 'HVN', 'CDB', 'IPT', 'BFM', 'MMH',
       'UIN', 'ISN', 'ART', 'YNG', 'FNL', 'UST', 'CLD', 'CEC', 'CIC',
       'FOE', 'LMT', 'MOD', 'IYK'], dtype=object)

In [ ]:
# Aggregated features (carrier/airport)
carrier_summary = df.groupby('carrier')['total_delay'].mean().reset_index().rename(columns={'total_delay':'avg_total_delay_per_carrier'})
airport_summary = df.groupby('airport')['total_delay'].mean().reset_index().rename(columns={'total_delay':'avg_total_delay_per_airport'})

In [ ]:
carrier_summary_sorted = carrier_summary.sort_values(
    by='avg_total_delay_per_carrier',
    ascending=False
)
carrier_summary_sorted.head(10)

   carrier  avg_total_delay_per_carrier
18      WN                 11188.673778
1       AA                  8782.900203
15      UA                  6248.942301
3       B6                  6091.326271
11      NK                  4808.278416
4       DL                  4739.592217
16      US                  3809.885246
5       EV                  3462.522989
13      OO                  3409.723040
17      VX                  3358.926743

In [ ]:
airport_summary_sorted = airport_summary.sort_values(
    by='avg_total_delay_per_airport',
    ascending=False
)
airport_summary_sorted.head(10)

    airport  avg_total_delay_per_airport
270     ORD                 28688.190510
103     DFW                 26513.337218
23      ATL                 23149.151656
102     DEN                 21660.027842
334     SFO                 19627.079536
197     JFK                 18018.248421
333     SFB                 17022.191176
208     LAX                 17013.331395
126     EWR                 16293.311213
231     MCO                 15004.339864

# **LOAD**

In [ ]:
save_path='/content/drive/MyDrive/Data_Pipeline/Transformed_Airline_Delay_Cause.csv'

In [ ]:
# Save DataFrame as CSV
df.to_csv(save_path, index=False)